#!/bin/sh


MARKUP='<span foreground="$FG" size="medium">$TXT</span>'

test -z "$(nordvpn status | awk -F ': ' '$1 ~ "Status" && $2 == "Connected" {print $2}')" \
    && echo $MARKUP | FG='#7F9183' TXT='off' envsubst \
    || echo $MARKUP | FG='#DA4167' TXT='ON!' envsubst
